import Table from 'component/table'
import Head from 'next/head'
import { FiPlusCircle } from 'react-icons/fi'
import Form from 'component/form'
import { useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { toogleChangeAction, deleteAction } from '../redux/reducer'
import {deleteUser, getUsers} from '../lib/helper';
import { useQueryClient } from 'react-query';


export default function Home() {

  const visible = useSelector((state) => state.app.client.toogleForm)
  const deleteId = useSelector(state => state.app.client.deleteId)
  const queryclient = useQueryClient();

  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toogleChangeAction());
    console.log('clicked')
  };

  const deletehandmler = async () => {
    if(deleteId) {
      await deleteUser(deleteId);
      await queryclient.prefetchQuery('users', getUsers)
      await dispatch(deleteAction(null))
    }
  }

  const cancelhandler = async () => {
    console.log("cancel")
    await dispatch(deleteAction(null));
  }

  return (
    <section>
    <Head>
      <title>CRUD Application</title>
      <meta name='description' content='Generated by create Next App'/>
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className='py-5'>
    <div className="container mx-auto p-2 border-2 rounded-md">
      <h1 className='text-2xl font-bold text-center text-black py-10'> LOG ERROR </h1>
      <div className="container mx-auto flex justify-between py-5 pl-2 border-2 rounded-md">
        <div className="left flex gap-3">
          <button onClick={handler} className='bg-green-500 text-white px-4 py-2 border rounded-md hover:border-yellow-400 hover:bg-green-600'>
            Add data<span className='px-1'><FiPlusCircle size={20} className='inline-block my-1'></FiPlusCircle></span>
          </button>
        </div>
        { deleteId ? DeleteComponent({deletehandler, cancelhandler}) : <></>}
      </div>

        {/* Form */}
          {visible ? <Form></Form> : <></>}
        {/* form end */}

        {/* table */}
        <div className='container mx-auto max-w-screen flex justify-between py-2 px-2 border-2 rounded-md'>
          <Table></Table> 
        </div>
        {/* table end */}
    </div>
    </main>
    </section>
  )
}

function DeleteComponent({ deletehandler, cancelhandler}){
  return (
    <div className='flex gap-5'>
      <button>sure?</button>
      <button onClick={deletehandler} className='flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:text-gray-50'>yes</button>
      <button onClick={cancelhandler} className='flex bg-yellow-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:text-gray-50'>no</button>
    </div>
  )
}
